# These are examples of compilping commands in linux system.
COMPILER = g++
LIBS =
LINKS =
FLAGS =  -O2 -Wall -std=c++11
problem771 : problem771.cpp
	$(COMPILER) $(FLAGS) $(LIBS) -o $@.out $^ $(LINKS)
problem762 : problem762.cpp
	$(COMPILER) $(FLAGS) $(LIBS) -o $@.out $^ $(LINKS)
problem292 : problem292.cpp
	$(COMPILER) $(FLAGS) $(LIBS) -o $@.out $^ $(LINKS)
problem521 : problem521.cpp
	$(COMPILER) $(FLAGS) $(LIBS) -o $@.out $^ $(LINKS)
problem695 : problem695.cpp
	$(COMPILER) $(FLAGS) $(LIBS) -o $@.out $^ $(LINKS)
problem429 : problem429.cpp
	$(COMPILER) $(FLAGS) $(LIBS) -o $@.out $^ $(LINKS)
problem896 : problem896.cpp
	$(COMPILER) $(FLAGS) $(LIBS) -o $@.out $^ $(LINKS)
problem824 : problem824.cpp
	$(COMPILER) $(FLAGS) $(LIBS) -o $@.out $^ $(LINKS)
problem696 : problem696.cpp
	$(COMPILER) $(FLAGS) $(LIBS) -o $@.out $^ $(LINKS)
problem892 : problem892.cpp
	$(COMPILER) $(FLAGS) $(LIBS) -o $@.out $^ $(LINKS)
problem888 : problem888.cpp
	$(COMPILER) $(FLAGS) $(LIBS) -o $@.out $^ $(LINKS)
problem812 : problem812.cpp
	$(COMPILER) $(FLAGS) $(LIBS) -o $@.out $^ $(LINKS)
problem784 : problem784.cpp
	$(COMPILER) $(FLAGS) $(LIBS) -o $@.out $^ $(LINKS)
